### ISSUE TITLE
类似备注的文本框？

### ISSUE THREAD

**Issue by tsengkasing** [CyanSalt/todu#1]
除了可以添加今天和明天要做的事情，是否可以有一块地方，可以填写一些需要详细的文字描述的部分，就在页面的下部空白处？

比如下面这样的？

![image](https://user-images.githubusercontent.com/10103993/30871259-cc1d89d8-a318-11e7-9c91-ddcd888121df.png)

**Comment by CyanSalt** [comment]
[1.6.0](https://github.com/CyanSalt/todu/releases/tag/v1.6.0) 发布啦，感觉可以用这个实现：

![_20171103181517](https://user-images.githubusercontent.com/5101076/32376551-125cccee-c0e0-11e7-83f0-7a17d34eafdf.png)

（在描述栏按shift+回车可以呼出备注）
为了实现 textarea autosize 也真是不容易呢，不知道为什么敲回车的时候会闪一下

**Comment by tsengkasing** [comment]
well done!
