### ISSUE TITLE
Icon used in makefile.js not functioning

### ISSUE THREAD

**Issue by kczx3** [CyanSalt/todu#4]
I noticed the ico file targeted for use with electron-packager has an extension of .ico_.  Thus, when building, the executable has the Electron icon instead.  If I change the file extension to .ico then the build process doesn't seem to work.  Though there are no errors in the console that I see.

**Comment by CyanSalt** [comment]
@kczx3 that `.ico_` is a plain text file contains the icon file's link. You can download it and then rename it to `.ico`.
I just don't want to put the static files into the repo because of speed of cloning. XD

**Comment by kczx3** [comment]
I didn't realize that file had a URL in it.  I downloaded the zip from it but no matter what icon I use, it never works when I try to build the package.  The dist folder never gets created.

On a side note, what is the best way to keep my storage files from disappearing when I have to rebuild the application?  As it stands now, I have to keep a copy of the json files outside the project and then create the storage folder in the built app and copy the json files there.

**Comment by CyanSalt** [comment]
I think the icons you downloaded are all `.png`. The icon i use is packaged in releases [here](https://github.com/CyanSalt/todu/releases). You can download any of them and find the icon file.
*(And I also upload one for you **[here](https://github.com/CyanSalt/todu/releases/download/v1.5.0/icon.ico)**. You can just download it.)*

If you want to keep your storage folder whenever the app is re-compiled, the best way is to modify the storage module if you **want** to code yourself.

To solve the issue #3 , you can add these code to `src/plugin/storage.js`:
```js
// on the head
import {remote} from 'electron'

// comment the old PATH and add new
// const PATH = ...
const PATH = remote.app.getPath('appData')
```

**Comment by kczx3** [comment]
> If you want to keep your storage folder whenever the app is re-compiled, the best way is to modify the storage module if you want to code yourself.

This was partly why I thought placing the storage in App_Data would be better.  So that it doesn't get overwritten.  I assume that the storage doesn't get lost when I do an update through the application itself?

Also, thanks for providing the icon!
