### ISSUE TITLE
Days seem to be 1 off

### ISSUE THREAD

**Issue by kczx3** [CyanSalt/todu#6]
The day numbers and days of the week appear to be off by one for me.  Not sure why and in looking at dateFormatter.js, I don't see anything that makes me think that would be occurring.

**Comment by CyanSalt** [comment]
Eh, is it possible for you to open this app, press `ctrl+shift+I`, select `console` and input `new Date().toLocaleString()`? It should print the correct time, otherwise it seems to be a bug of Electron framework.

**Comment by kczx3** [comment]
Running the suggested does output the correct date and time in the console.

**Comment by kczx3** [comment]
I think the problem is related to `standard()` inside of date-formatter.js.  You return the date string in ISO format.  Thus, when you pass that string back to `format()`, it creates a Date object in UTC.  You really want to be returning a local string, right?  You have something like this [here](https://github.com/CyanSalt/todu/blob/master/src/component/date-formatter.js#L4)

**Comment by CyanSalt** [comment]
Excellent! I haven't realized this issue because I live in the Eastern Hemisphere 🌏 . Fixed by [this commit](https://github.com/CyanSalt/todu/commit/dbfef2).

**Comment by kczx3** [comment]
Works great now!  Thanks very much!
